name: Quality assurance

on: [push, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            cwd: ./
            args: [--frozen-lockfile]
          version: ${{ env.PNPM_VERSION }}

      - name: Check scripts code style
        run: pnpm lint:scripts

      - name: Check styles code style
        run: pnpm lint:styles

      - name: Check code style with Prettier
        run: pnpm lint:prettier
